# Sentiment Analysis
#### By Rohit Suryavanshi
Work Timeline doc: https://docs.google.com/document/d/1IXqmf_iipkzNDwZqWczPdeCnnNbQvESU1ktOREng1D0/edit?usp=sharing

In [1]:
import numpy as np
#from numpy.random import *
import pandas as pd
#import math
import nltk
#nltk.download()

In [4]:
df=pd.read_csv('training.csv')

### Labels:

0.   sadness
1.   joy
2.   love
3.   anger
4.   fear
5.   surprise

In [5]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
from nltk.tokenize import sent_tokenize

# Pre-Processing

## Remove Punctuations
#### Ref: https://studymachinelearning.com/text-preprocessing-removal-of-punctuations/

In [6]:
import string
regular_punct = list(string.punctuation)
def remove_punctuation(text):
    punct_list = regular_punct
    for punc in punct_list:
        if punc in text:
            text = text.replace(punc, ' ')
    return text.strip()
df['punc_text']=df['text'].apply(remove_punctuation)

## Tokenising Text

In [7]:
df['tokenised']=df.apply(lambda row: nltk.word_tokenize(row['punc_text']), axis=1)

## Lemmatization

In [8]:
from nltk.stem import PorterStemmer
# init stemmer
porter_stemmer=PorterStemmer()
from nltk.stem import WordNetLemmatizer
#nltk.download('wordnet')
# init lemmatizer
lemmatizer = WordNetLemmatizer()

### Position Tagging

In [9]:
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    elif treebank_tag.startswith('R'):
        return wordnet.ADV
    else:
        return ''

In [10]:
# df.apply(.....) ## to get whole lemmatized with pos_tagging

In [11]:
text=df['tokenised']
text=text.tolist()
for i in range(len(text)):
    #tokens =  text[i]   #a['tokenised'][i]
    #tag=nltk.pos_tag(tokens)
    #for j in range(len(tokens)):
    text[i]=[lemmatizer.lemmatize(word=word,pos='v') for word in text[i]]
df['lemmatized']= pd.Series((i for i in text))
#df['lemmatized']= pd.Series((i for i in text))    


#df['lemmatized']=df['tokenised'].progress_apply(lambda word: lemmatizer.lemmatize(word=word,pos='v') ) 
#df['lemmatized'] = df['tokenised'].apply(lambda x: x= [word for word in x.split() word=lemmatizer.lemmatize(word=word,pos='v')])

## Removal of Stopwords
##### Ref: https://stackabuse.com/removing-stop-words-from-strings-in-python/#usingpythonsnltklibrary¶
##### Ref: https://stackoverflow.com/questions/29523254/python-remove-stop-words-from-pandas-dataframe

In [12]:
# from nltk.corpus import stopwords
# #nltk.download('stopwords')
# text=df['lemmatized']
# text=text.tolist()
# n=len(df['lemmatized'])
# for i in range(n):
#     text[i] = [word for word in df['lemmatized'][i] if not word in stopwords.words()]    
# df['cleaned_text']= pd.Series((i for i in text))
# df.head()
# Use
#df.apply[lambda x: ]

#print(test)

In [13]:
stop = stopwords.words('english')
df['string_text']= df['lemmatized'].str.join(" ")
df['cleaned_text'] = df['string_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

###### Sample to use df.apply on dataframe

In [14]:
# from nltk.corpus import stopwords
# stop = stopwords.words('english')

# pos_tweets = [('I love this car', 'positive'),
#     ('This view is amazing', 'positive'),
#     ('I feel great this morning', 'positive'),
#     ('I am so excited about the concert', 'positive'),
#     ('He is my best friend', 'positive')]

# test = pd.DataFrame(pos_tweets)
# test.columns = ["tweet","class"]

# # Exclude stopwords with Python's list comprehension and pandas.DataFrame.apply.
# #test['tweet_without_stopwords'] = test['tweet'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
# print(test['tweet'].tolist())

### New Dataset with Pre-Processed Text

In [15]:
new_df = pd.DataFrame(df['cleaned_text'])
new_df['label']=df['label']
new_df.to_csv('pre-processed_data.csv',index=False)
#len(new_df)

##### Sample to use classifier

In [16]:
# from sklearn.datasets import load_iris
# from sklearn.model_selection import train_test_split
# from sklearn.naive_bayes import GaussianNB
# X, y = load_iris(return_X_y=True)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# type(X_train)
# gnb = GaussianNB()
# y_pred = gnb.fit(X_train, y_train).predict(X_test)
# print(y_pred,y_test)

## Basic Way to Approach
1. Splitting dataframe in 80-20 way for training and test(C.V.) datasets
2. Import TF-IDF vectorizer and corpus from x_train and x_test
3. Apply vectorizer on corpus and obtain array containing TF-IDF values for each word
4. Apply Complement Naive Bayes

In [160]:
## Splitting into training and test(C.V.) data set
# sc=0
# while sc<0.94:
n=len(new_df['label'])
idx_train = np.random.choice(n,int(n),replace=False) ## Gives us a list
#idx_test = np.random.choice(n,int(n*0.2),replace=False) ## int bcuz n*0.2 is float

In [161]:
df_train=new_df.loc[idx_train]
x_train=df_train['cleaned_text']
y_train=df_train['label']

In [162]:
# df_train,df_test=new_df.loc[idx_train],new_df.loc[idx_test]
# x_train,x_test=df_train['cleaned_text'],df_test['cleaned_text']
# y_train,y_test=df_train['label'],df_test['label']

In [163]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

corpus_train=x_train.tolist()
#corpus_test=x_test.tolist()

vectorizer =  CountVectorizer() 
#vectorizer =  TfidfVectorizer()

X_train = vectorizer.fit_transform(corpus_train)
#X_test = vectorizer.transform(corpus_test)
#type(X_train)
vocab=vectorizer.get_feature_names_out()
vocab_size=len(vocab)

# Deep Learning
### Used Tensorflow and Keras

In [164]:
import tensorflow 
from tensorflow import keras

In [165]:
## Max length(words) in a sentence
print(max(corpus_train))
max_length=24 ## counted by hand

zoom difficulties feel like give everything feel helpless alone desert cast ways voice action others another story zoom also temporarily loose view full picture


### Used One-hot Encoding and Padding to input it into Embedding Layer

In [166]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

encoded=[one_hot(i,vocab_size) for i in corpus_train]
padded=pad_sequences(encoded,maxlen=max_length,padding='post')

In [167]:
x=padded
#x=encoded
#length = max(map(len, x))
#x=np.array([xi+[None]*(length-len(xi)) for xi in x])
#X=np.asarray(x,dtype=object)
#print(x)
#print(type(x))
y=y_train.values

### Developing Model

In [187]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import GlobalAveragePooling1D
from tensorflow.keras.layers import Conv2D

embeded_vector_size=50
model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
#model.add(Flatten())
#model.add(Conv1D(64,kernel_size=(50,50),activation='relu'))
model.add(GlobalAveragePooling1D())
model.add(Dense(units=16,activation='relu'))
model.add(Dense(6, activation='softmax'))

In [169]:
model.compile(optimizer='adam',loss=keras.losses.SparseCategoricalCrossentropy(),metrics=['accuracy'])
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 24, 50)            605350    
_________________________________________________________________
global_average_pooling1d_9 ( (None, 50)                0         
_________________________________________________________________
dense_16 (Dense)             (None, 8)                 408       
_________________________________________________________________
dense_17 (Dense)             (None, 6)                 54        
Total params: 605,812
Trainable params: 605,812
Non-trainable params: 0
_________________________________________________________________


In [170]:
model.fit(x, y, epochs=2, batch_size=1)

Epoch 1/2
16000/16000 [==============================] - 60s 4ms/step - loss: 0.9976 - accuracy: 0.6401
Epoch 2/2
16000/16000 [==============================] - 61s 4ms/step - loss: 0.4187 - accuracy: 0.8554


In [171]:
loss,accuracy=model.evaluate(x,y)
accuracy

500/500 [==============================] - 1s 648us/step - loss: 0.2914 - accuracy: 0.9144


0.9143750071525574

In [172]:
df_test=pd.read_csv('test.csv')
## REMOVE PUNCTUATION
df_test['text']=df_test['text'].apply(remove_punctuation)
## TOKENISATION
df_test.text=df_test.apply(lambda row: nltk.word_tokenize(row['text']), axis=1)
## LEMMATIZATION
submit=df_test['text']
submit=submit.tolist()
for i in range(len(submit)):
    submit[i]=[lemmatizer.lemmatize(word=word,pos='v') for word in submit[i]]
## REMOVE STOPWORDS
submit=pd.Series(submit)
df_test['string_text']= submit.str.join(" ")
df_test['cleaned_text'] = df_test['string_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
submit=df_test['cleaned_text']

In [173]:
corpus_submit=submit.tolist()
 
vectorizer =  CountVectorizer() 

submit_hmm = vectorizer.fit_transform(corpus_submit)
#X_test = vectorizer.transform(corpus_test)
#type(X_train)
vocab=vectorizer.get_feature_names_out(submit_hmm)
vocab_size=len(vocab)

In [174]:
#print(max(corpus_submit))
max_length=24

In [175]:
encoded_submit=[one_hot(i,vocab_size) for i in corpus_submit]
submit=pad_sequences(encoded_submit,maxlen=max_length,padding='post')
#submit=encoded_submit

In [176]:
p=model.predict(submit)
#print(p[:7])
# p[np.where(a==np.max(p))] = 1
b = np.zeros_like(p)
b[np.arange(len(p)), p.argmax(1)] = 1
kaggle=b
# kaggle=np.round(p)
# kaggle = p
#print(kaggle[0:7])
def labelling(matrix):
    n=len(matrix)
    lst=[1]*n
    for i in range(n):
        arr=matrix[i]
        arr=list(arr)
        idx=arr.index(max(arr))
        lst[i]=idx        
    return lst
a=labelling(kaggle)        


In [177]:
kaggle=pd.DataFrame(columns=['id','label'])
n=len(a)
k=np.arange(n)+1
kaggle['id']=pd.Series(k)
kaggle['label']=pd.Series(a)
len(kaggle['id'])
kaggle.to_csv('submission_tensor.csv',index=False)

# Naive Bayes Implementation

#### Implemented Scaling - Decreased Accuracy

In [23]:
from sklearn import preprocessing
# scaler1 = preprocessing.StandardScaler(with_mean=False).fit(X_train) ## in [-2,2]
# scaler2 = preprocessing.StandardScaler(with_mean=False).fit(X_test) ## with_mean=False is used for sparse matrices
# X_train_scaled = scaler1.transform(X_train)
# X_test_scaled = scaler2.transform(X_test)

# min_max_scaler = preprocessing.MinMaxScaler() # to fit array in [0,1] range

# min_max_scaler = preprocessing.MaxAbsScaler()
# # This estimator scales and translates each feature individually such that the maximal absolute value of each feature 
# # in the training set will be 1.0. 
# # It does not shift/center the data, and thus does not destroy any sparsity.
# # This scaler can also be applied to sparse CSR or CSC matrices.

# X_train_scaled = min_max_scaler.fit_transform(X_train)
# X_test_scaled = min_max_scaler.fit_transform(X_test)

# X_train_scaled.array
# X_test_scaled.toarray()
# y_train.array
# y_test.array

X_train_scaled=X_train
#X_test_scaled=X_test

In [ ]:
from sklearn.naive_bayes import BernoulliNB ## something new score - 0.7
from sklearn.naive_bayes import CategoricalNB ##sparse error 
from sklearn.naive_bayes import GaussianNB ##sparse error
from sklearn.naive_bayes import ComplementNB ## dimension mismatch - max_score - 0.933125
from sklearn.naive_bayes import MultinomialNB ## dimension mismatch - 0.8

model = ComplementNB() ## 0.7240

### ENSEMBLE LEARNING
##### Decreased Accuracy since Complement NB was way stronger than multi and Bernoulli

In [ ]:
### ENSEMBLE LEARNING

# model2 = MultinomialNB() ## 0.61
# model3 = BernoulliNB() ## 0.61400
# Cnb=model1.fit(X_train_scaled, y_train)
# Mnb=model2.fit(X_train_scaled, y_train)
# Bnb=model3.fit(X_train_scaled, y_train)

# from sklearn.ensemble import VotingClassifier
# #create a dictionary of our models
# estimators=[('Complement', Cnb), ('Multinomial', Mnb), ('Bernoulli', Bnb)]
# #create our voting classifier, inputting our models
# ensemble = VotingClassifier(estimators, voting='hard')
# submission=ensemble.fit(X_train_scaled, y_train)
# ensemble.score(X_test_scaled, y_test)

In [24]:
submission=model.fit(X_train_scaled, y_train) 

In [25]:
df_test=pd.read_csv('test.csv')
## REMOVE PUNCTUATION
df_test['text']=df_test['text'].apply(remove_punctuation)
## TOKENISATION
df_test.text=df_test.apply(lambda row: nltk.word_tokenize(row['text']), axis=1)
## LEMMATIZATION
submit=df_test['text']
submit=submit.tolist()
for i in range(len(submit)):
    submit[i]=[lemmatizer.lemmatize(word=word,pos='v') for word in submit[i]]
## REMOVE STOPWORDS
submit=pd.Series(submit)
df_test['string_text']= submit.str.join(" ")
df_test['cleaned_text'] = df_test['string_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))
submit=df_test['cleaned_text']


In [26]:
n=len(submit)
corpus_submit=submit.tolist()
submit = vectorizer.transform(corpus_submit)
#submit_scaled = min_max_scaler.fit_transform(submit)
submit=submission.predict(submit)
kaggle=pd.DataFrame(columns=['id','label'])
k=np.arange(n)+1
kaggle['id']=pd.Series(k)
kaggle['label']=pd.Series(submit)
len(kaggle['id'])
kaggle.to_csv('submission_corrected.csv',index=False)

## WITHOUT SCALING - 0.73400, IMPROVES BY 0.1
## WITH SCALING, DOWN BY 0.01 FOR MAX ABS 
##               DOWN BY 0.12 FOR STANDARD SCALER  
## WITHOUT STOPWORDS - 0.654
## USING COUNT_VECTORIZER - 0.674
## with full dataset as train - 0.728 and score - 0.93
## BY REPETITION, 0.74200
## Spell checker and contractions brings down score
## CURRENT - FULL SET AND ADDED PUNCTUATIONS - increase by 0.004

In [24]:
import tensorflow as tf
from tensorflow import keras
#from tensorflow.keras import layers

In [25]:
x = tf.constant([[1., 2., 3.],
                 [4., 5., 6.]])
print(x)
print(x.shape)
print(x.dtype)
x @ tf.transpose(x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [27]:
tdf=pd.read_csv('play_data.csv')
y=tdf.label.values
x=np.column_stack((tdf.YearsExperience.values,tdf.Salary.values))
np.random.shuffle(x)  
#type(x)

In [29]:
#np.random.choice()
model=keras.Sequential([keras.layers.Dense(16,input_shape=(2,),activation='relu'),keras.layers.Dense(2,activation='relu')])
model.compile(optimizer='adam',loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])
model.fit(x,y,batch_size=16)

2/2 [==============================] - 2s 58ms/step - loss: 0.6931 - accuracy: 0.4667


In [72]:
x=X_train.toarray()
y=y_train.values
print(x.shape)

(16000, 12107)


In [83]:
model=keras.Sequential([keras.layers.Dense(16,input_shape=(12107,),activation='relu'),keras.layers.Dense(6,activation='relu')])
model.compile(optimizer='adam',loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),metrics=['accuracy'])
y=new_df.label.values
model.fit(x[0:1000],y[0:1000],batch_size=1)

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.